services:
  split-service:
    build: ./split-service
    container_name: split-service
    volumes:
      - ./split-service/chunks:/app/chunks

  whisper-service:
    build: ./whisper-service
    container_name: whisper-service
    environment:
      - WHISPER_MODEL=turbo
    volumes:
      - ./split-service/chunks:/app/chunks

  pipeline-service:
    build: ./pipeline-service
    container_name: pipeline-service
    ports:
      - "8002:8002"
    depends_on:
      - split-service
      - whisper-service
