services:
  ollama:
    build : ./ollama
    image: my-ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    gpus: all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  split-service:
    build: ./split-service
    container_name: split-service
    volumes:
      - ./split-service/chunks:/app/chunks

  whisper-service:
    build: ./whisper-service
    container_name: whisper-service
    environment:
      - WHISPER_MODEL=turbo
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./split-service/chunks:/app/chunks
    restart: unless-stopped
    gpus: all

  pipeline-service:
    build: ./pipeline-service
    container_name: pipeline-service
    ports:
      - "8002:8002"
    depends_on:
      - split-service
      - whisper-service
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_db
    volumes:
      - ./data:/app/data

  workflow_manager:
    build: ./workflow_manager
    container_name: c_workflow_manager
    ports:
      - "5000:5000"
    env_file:
      - ./workflow_manager/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./data:/app/data

  db:
    image: postgres:15
    container_name: postgres-ai
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ai
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
  ollama: