services:
  split-service:
    build: ./split-service
    container_name: split-service
    volumes:
      - ./split-service/chunks:/app/chunks

  whisper-service:
    build: ./whisper-service
    container_name: whisper-service
    environment:
      - WHISPER_MODEL=turbo
    volumes:
      - ./split-service/chunks:/app/chunks

  pipeline-service:
    build: ./pipeline-service
    container_name: pipeline-service
    ports:
      - "8002:8002"
    depends_on:
      - split-service
      - whisper-service
    volumes:
      - ./split-service/data:/app/data

  workflow_manager:
    build: ./workflow_manager
    network_mode: "host"
    container_name: c_workflow_manager
    env_file:
      - ./workflow_manager/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./split-service/data:/app/data